### ISSUE TITLE
Left Click / Right Click Mouse Issue

### ISSUE THREAD

**Issue by Skylord2016** [Wooza/ProspectTogether#24]
**Vintage Story Version:** V1.21.6
**Server Version:** V1.21.6
**Prospect Together Mod Version:** V2.1.2
**Relevant Error Log:** N/A
**Computer OS:** Windows 11

The past few days, I've been having weird, unpredictable issues with the left & right click mouse buttons not working. The buttons would work on the main VS menu, everything else on my PC, and when holding ALT ingame to get the alternative mouse mode. However, not normally ingame, I cannot pick anything up, or mine anything. 
I fixed it briefly by changing between Windowed mode & Fullscreen, but that then broke again yesterday, it was briefly fixed by me resizing my window to about half my desktop screen. 
Frustrated with only being able to play with half a screen, I completely uninstalled reinstalled Vintage Story, and completely reinstalled all my mods. No change. I borrowed a different mouse, but again no luck. I then disabled off all my mods and 1 by 1 turned them back on until the bug appeared. _Testing within a creative single player world everytime to see if I could use my left/right click normally._ 

**The left & right click then broke when I enabled Prospect Together. To double check, I disabled all mods, and then enabled JUST Prospect Together & again the mouse buttons broke.** 

I honestly have no idea how Prospect Together is causing this, my best guess is V1.21.6 broke a few mod's GUIs (Such as Vinconomy) and it might be something related to that? But I don't have experience with this, I'm just throwing out a suggestion. 

I have checked all my recent log files, and there is nothing mentioned ProspectTogether. No crash reports as it does not cause the game to crash just a "locking" effect on the mouse 1 & 2 controls. 

I have been using your mod for around 8 months with no issues, until the back couple of days when me and my friends updated our server to V1.21.6 & made a new world. None of the other players on the server have reported the same issue and from checking the Vintage Story Discord, no-one else has mentioned this same issue I am experiencing. And as I said previously, my only fix currently is disabling ProspectTogether. 

Any advice or suggestions would be much appreciated as well could you please check whether you need to do any patches for ProspectTogether for V1.21.6 as it's currently versioned for V1.21.5. 

Many thanks,
Sky

**Comment by Wooza** [comment]
Hi @Skylord2016,

first of all, thanks for the detailed error report. I really appreciate the effort you put into it :)

I was unable to reproduce the error that you are facing with a mostly identical setup (Win11, Game 1.21.6, Mod 2.1.2).
However, your bug description reminds of me #12.
AFAIK, the bug which caused #12 is still present in the game. Essentially, the game does not seem to properly remove dialogs when they are hidden, e..g, when closing the map.
So for example if you arrange the map dialogs like this, where the ProspectTogether Dialog is roughly at the middle of your screen and then hide the map, then left or right mouse clicks will not work properly.
<img width="2559" height="1439" alt="Image" src="https://github.com/user-attachments/assets/059193aa-9de4-4af6-a637-8450e76a43b0" />

Can you open your Map with M and move all the dialogs/windows around and check if there is something directly at the center of the screen? If so, try to move it somewhere else. Hopefully this should fix your problem. This might also be the reason, why it worked for a while when resizing the window. If this fixes your problem, I would appreciate it if you could open a bug at https://github.com/anegostudios/VintageStory-Issues, because the same bug also occurs with the in-game prospecting dialog.

**Comment by jasminedevv** [comment]
Completely different person here also wondering why my left and right mouse buttons suddenly stopped working in Vintage Story only. I also could not use the bottom half of the main menu. I was able to fix this using @Wooza's suggestions above. I think you are correct that this is related to #12.

I opened my map and dragged it to the side. There was this window behind it:

<img width="1231" height="784" alt="Image" src="https://github.com/user-attachments/assets/2e31e3ab-6b77-407d-a666-e8a86156f396" />

I dragged that PropectTogether window back to the side like this:

<img width="1675" height="919" alt="Image" src="https://github.com/user-attachments/assets/3537c67c-6ede-43cd-b050-3d41610dd7ec" />

and that fixed the issue. Thanks!

**Comment by felixshiftellecon** [comment]
We ran into this issue on the Steam Deck today. For anyone there, you may need to set the UI scale to the smallest setting to be able to see/move the hidden window.

Appreciate you reporting this so we could find it @Skylord2016

**Comment by Skylord2016** [comment]
Hi @Wooza, 

You were absolutely bang on there with it being related to issue 12. I fixed it shortly after you replied by doing as you said, moving the UIs to find the UI hidden behind, closing it and getting the mouse focus back. 

I'll chuck an issue on the VS github reporting the bug and link it to this when I next get some free time :)

Sorry for such a delay replying, it's been one hell of a start to 2026.
_Thanks, take care, Sky_

Closing and marking as resolved.

**Comment by Wooza** [comment]
Someone ran into the same bug again so I created a bug ticket here https://github.com/anegostudios/VintageStory-Issues/issues/8874
Edit: Reopening this ticket as long as the game bug is not fixed, so people can find it more easily
